### ISSUE TITLE
New Account Creation Not Redirecting to Landing Page

### ISSUE THREAD

**Issue by dev-phantom** [Praisecodes/dentask#13]
### Description:
When users create a new account on the platform, the current behavior is that they remain on the "Create Account" page after successfully creating their account. This issue addresses the need to redirect users to an appropriate landing page after a successful account creation.

**Problem Statement:**

After successfully creating a new account, users are not redirected to the landing page or any other relevant destination. They remain on the "Create Account" page, which can be confusing and doesn't provide a seamless user experience.

**Proposed Changes:**

1. Implement a redirection mechanism that automatically takes users to the landing page upon successful account creation.
2. Ensure that users are greeted with a clear message or confirmation on the landing page, acknowledging their successful account creation.

**Acceptance Criteria:**

- After creating a new account, users should be automatically redirected to the landing page.
- The redirection should be seamless and not cause any disruption to the user's flow.
- A confirmation message or notification should be displayed on the landing page to inform users about their successful account creation.
- The redirection should work correctly across different devices and browsers.

**Labels:**
- User Experience
- Account Creation
- Redirection
- Enhancement

**Comment by Praisecodes** [comment]
This doesn't work yet!
