### ISSUE TITLE
Bug: fix general responsiveness on mobile view 

### ISSUE THREAD

**Issue by dev-phantom** [Praisecodes/dentask#4]
### Currently on mobile view we have this
![Screenshot_20231001-232648](https://github.com/Praisecodes/dentask/assets/72051159/36a58524-9305-42f8-9951-d865d687a7c3)

### suggested fix 
Reduce the text size and button
And reduce the paddings in the get started page

**Comment by Praisecodes** [comment]
All Done my bro

**Comment by dev-phantom** [comment]
> All Done my bro

This issue was not resolved In the last commit although I added some hints and new issues in the commit created

I suggest you create a PR this help track the progress of this issue and link the issue to it
