### ISSUE TITLE
Enhancement: Improve Commit Message Descriptiveness

### ISSUE THREAD

**Issue by dev-phantom** [Praisecodes/dentask#7]
**Issue Description:**
Currently, the last project's commit messages lack descriptive titles, making it challenging to understand the purpose and context of each commit. This hinders collaboration, code review, and the ability to track changes effectively. To enhance the quality of our commit history, we should establish guidelines for writing more informative commit titles.

**Proposed Solution:**
1. **Guidelines:** Create clear and concise guidelines for writing commit titles that convey the intent of the changes made in the commit.

2. **Enforcement:** Encourage contributors to adhere to these guidelines through code review comments and automated checks.

3. **Documentation:** Document the commit message guidelines in our project's README or CONTRIBUTING.md file, making them easily accessible to all contributors.

4. **Education:** Provide resources or training for team members and contributors to understand the importance of descriptive commit titles and how to write them effectively.

**Expected Benefits:**
- Enhanced code review process.
- Improved collaboration among team members.
- Easier tracking of changes and bug fixes.
- Better project maintainability.

**Additional Information:**
- We should consider examples of good and bad commit titles to illustrate the difference.
- Determine whether we want to enforce these guidelines strictly or provide flexibility in certain cases.

 
![Screenshot_20231002-001004](https://github.com/Praisecodes/dentask/assets/72051159/1678082d-5bd6-4d9a-a345-fe7cb082f4bd)

**Comment by Praisecodes** [comment]
Shey no be to kuku flog you for this one bawo?

**Comment by dev-phantom** [comment]
@Praisecodes I strongly recommend reopening this issue until Husky has been installed. 

**Reason:** 

Husky plays a crucial role in improving the quality of our GitHub commit messages. By incorporating Husky, we can enforce commit message standards and guidelines, ensuring that commit messages are more descriptive and follow a consistent format. This consistency is essential for better collaboration, code review, and tracking changes effectively.

Husky can be configured to run pre-commit hooks that check commit messages against predefined rules, such as enforcing a minimum length, ensuring they are in a specific format, or even integrating with tools like linters to catch potential issues early.

Installing Husky will not only enhance our development process but also help maintain a cleaner and more organized commit history, which is valuable for project maintainability in the long run.

Please reopen this issue and proceed with the installation of Husky to ensure our commits are of higher quality.
